channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - numpy
  - matplotlib
  - uproot
  - awkward
  - numba
  - pip
  - pytables
  - ipython
  - root
  - filelock
  - scikit-optimize
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - pip:
    - absl-py
    - appdirs
    - astunparse
    - awkward
    - awkward-cpp
    - cachetools
    - certifi
    - charset-normalizer
    - click
    - docker-pycreds
    - docutils
    - flatbuffers
    - gast
    - gitdb
    - gitpython
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - h5py
    - idna
    - importlib-metadata
    - law
    - libclang
    - lockfile
    - luigi
    - markdown
    - markupsafe
    - ml-dtypes
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvcc-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - oauthlib
    - opt-einsum
    - packaging
    - protobuf
    - pyasn1
    - pyasn1-modules
    - python-daemon
    - pyyaml
    - requests
    - requests-oauthlib
    - rsa
    - sentry-sdk
    - setproctitle
    - smmap
    - tenacity
    - termcolor
    - typing-extensions
    - urllib3
    - vector
    - wandb
    - werkzeug
    - wrapt
    - law
    - vector
    - mplhep
    - scinum
    - fsspec-xrootd
    - black
    - nflows
    - torchdiffeq
    - quickstats
