channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - numpy
  - matplotlib
  - uproot
  - awkward
  - numba
  - pip
  - pytables
  - ipython
  - root
  - scikit-optimize
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - pip:
    - h5py
    - law
    - luigi
    - vector
    - mplhep
    - scinum
    - nflows
    - torchdiffeq
    - quickstats
